---
name: deploy

on:

  release:
    types: [published]

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout.
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.x'

      - name: Make sure path are there also for act shells.
        if: ${{ env.ACT }}
        run: |
          echo "export PATH=\"/opt/hostedtoolcache/Python/${{ env.python_version }}/x64:/opt/hostedtoolcache/Python/${{ env.python_version }}/x64/bin:$PATH\"" >> /root/.bashrc

      - name: Upgrade pip.
        run: python -m pip install --upgrade pip

      - name: Install poetry and invoke.
        run: pip install poetry invoke

      - name: Configure poetry and pypi
        run: |
          poetry config virtualenvs.in-project true
          # Workaround since it won't take the token auth
          poetry config http-basic.pypi "__token__" "${{ secrets.PYPI_TOKEN }}"

      - name: Install the first python venv
        run: poetry install --no-dev

      - name: Build the package
        run: inv build

      - name: Deploy on pypi
        run: poetry publish
